AWSTemplateFormatVersion: '2010-09-09'
Description: 'Exampe API

  '
Globals:
  Function:
    Environment:
      Variables:
        AWS_ENVIRONMENT:
          Fn::Sub: ${AppEnv}
        VERSION: 2
    MemorySize: 256
    Runtime: python3.6
    Timeout: 180
Parameters:
  AppEnv:
    AllowedValues:
    - staging
    - production
    Default: staging
    Description: App Env
    Type: String
  AppName:
    Default: example-api
    Description: App Name
    Type: String
  BillingRef:
    Default: PROJECT-FOO
    Type: String
Resources:
  ExampleAPI:
    Properties:
      CodeUri: s3://nutile-sam/sam-build/69ba476f2d9d92f4a99f2bf77b71e041
      Environment:
        Variables:
          AppEnv:
            Ref: AppEnv
          AppName:
            Ref: AppName
      Events:
        PageCount:
          Properties:
            Method: get
            Path: /api/example
            RestApiId:
              Ref: RMMAPIGateway
          Type: Api
      FunctionName:
        Fn::Sub: ${AppName}-example-${AppEnv}
      Handler: main.hello
      MemorySize: 128
      Policies:
      - AWSLambdaExecute
      - AWSLambdaVPCAccessExecutionRole
      Runtime: python3.6
      Tags:
        billing_ref:
          Fn::Sub: ${BillingRef}
    Type: AWS::Serverless::Function
  RMMAPIGateway:
    Properties:
      Cors: '''*'''
      StageName: Prod
    Type: AWS::Serverless::Api
Transform: AWS::Serverless-2016-10-31
