AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Exampe API

Parameters:
  AppName:
    Type: String
    Default: 'example-api'
    Description: App Name
  AppEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
    Description: App Env
  BillingRef:
    Type: String
    Default: 'PROJECT-FOO'

#Define Global Settings for all functions
Globals:
  Function:
    Runtime: python3.6
    Timeout: 180
    MemorySize: 256
    Environment:
      Variables:
        AWS_ENVIRONMENT: !Sub ${AppEnv}
        VERSION: 002

## Basic api gateway
## No auth on thi## Have examples on githubwehbooks an
Resources:
  ExampleAPI:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.hello
      Runtime: python3.6
      CodeUri: .
      FunctionName: !Sub ${AppName}-example-${AppEnv}
      MemorySize: 128
      Tags:
        billing_ref: !Sub ${BillingRef}
      Policies:
        - AWSLambdaExecute
        - AWSLambdaVPCAccessExecutionRole
      Environment:
        Variables:
          AppEnv: !Ref AppEnv
          AppName: !Ref AppName
      Events:
        PageCount:
          Type: Api
          Properties:
            Path: /api/example
            RestApiId: !Ref RMMAPIGateway
            Method: get

  # ExampleCron:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: main.cron
  #     Runtime: python3.6
  #     CodeUri: .
  #     FunctionName: !Sub ${AppName}-cron-${AppEnv}
  #     MemorySize: 128
  #     Tags:
  #       billing_ref: !Sub ${BillingRef}
  #     Policies:
  #       - AWSLambdaExecute
  #       - AWSLambdaVPCAccessExecutionRole
  #     Environment:
  #       Variables:
  #         AppEnv: !Ref AppEnv
  #         AppName: !Ref AppName
  #     Events:
  #       Timer:
  #         Type: Schedule
  #         Properties:
  #           Schedule: rate(5 minutes)

  RMMAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
